media-user-token: "Aqz5qb7XBokhSjhQ9etWc9jltBQhyzM1RAYY5dnTELJXFJ1JTwjgFVW10hIWm33B2EtJCGOG6fiHZhdfy4waOcPSb5nK85ZpxaV/4PCzOy0eYkKto2E0MIdWChqNnyQ8Rz545O8QRhpPo6GuGG4E6hsgwxd3V4It1Yd/FDk/gh631cMmQc6N4EazqpjidTutjZA+gIhV9HaiR34mhHQiQjg1dSygQr6JKaSDWl7l423E5jD3Yg==" #If you need to obtain lyrics and aac-lc, need to change it
authorization-token: "your-authorization-token" #You don't need to change it; it can automatically obtain token
language: ""         #supportedLanguage by each storefront --> https://gist.github.com/itouakirai/c8ba9df9dc65bd300094103b058731d0
lrc-type: "lyrics"   #lyrics or syllable-lyrics
lrc-format: "lrc"   #lrc or ttml
embed-lrc: true
save-lrc-file: false
save-artist-cover: false
save-animated-artwork: true    # If enabled, requires ffmpeg
emby-animated-artwork: false    # If enabled, requires ffmpeg
embed-cover: true
cover-size: 5000x5000
cover-format: jpg       #jpg png or original
alac-save-folder: /content/drive/MyDrive/ALAC/
atmos-save-folder: /content/drive/MyDrive/ALAC/
aac-save-folder: AM-DL-AAC downloads
max-memory-limit: 256 # MB
decrypt-m3u8-port: "127.0.0.1:10020"
get-m3u8-port: "127.0.0.1:20020"
get-m3u8-from-device: true
#set 'all' to retrieve all m3u8, and set 'hires' to only detect hires m3u8.
get-m3u8-mode: hires # all hires
aac-type: aac-lc # aac-lc aac aac-binaural aac-downmix
alac-max: 192000  #192000 96000 48000 44100
atmos-max: 2768  #2768 2448
limit-max: 200
#{AlbumId} {AlbumName} {ArtistName} {ReleaseDate} {ReleaseYear} {UPC} {Copyright} {Quality} {Codec} {Tag} {RecordLabel}
#example: {ReleaseYear} - {ArtistName} - {AlbumName}({AlbumId})({UPC})({Copyright}){Codec}
album-folder-format: "{AlbumName} {Tag} [{ReleaseYear}] [{Codec}] [{Quality}]"
#{PlaylistId} {PlaylistName} {ArtistName} {Quality} {Codec} {Tag}
playlist-folder-format: "{PlaylistName}"
#{SongId} {SongNumer} {SongName} {DiscNumber} {TrackNumber} {Quality} {Codec} {Tag}
#example: Disk {DiscNumber} - Track {TrackNumber} {SongName} [{Quality}]{{Tag}}"
song-file-format: "{SongNumer}. {SongName}"
#{ArtistId} {ArtistName}/{UrlArtistName}
#if artist-folder-format set "",will not make artist folder
artist-folder-format: "{ArtistName} [ALAC]"
#if set "" will not add tag
explicit-choice : "[E]"
clean-choice : "[C]"
apple-master-choice : "[M]"
#if set true,for playlst,will use songinfo for meta #albumname track disk
use-songinfo-for-playlist: true
#if set true,will download album cover for playlist
dl-albumcover-for-playlist: true
mv-audio-type: atmos  #atmos ac3 aac
mv-max: 2160
